let suggestions=[
	//cse E-3
	
	"Artificial Intelligence",
	"Computer Networks",
	"Information Security",
	"Data Analytics",
	"Data Base Management System",
	"Compiler Design",
	"Soft Skills",
	"Signals And Systems",
	"Object Oriented Programming Using Java",
	"Formal Language & Automata Theory",
	"Operating Systems",
	"Principles of Marketing",
	"Personality Developement",
	"Graph Theory & Combinatorics", 
	"Data Mining",
	//civil E-3
	"Soil Mechanics",
	"Estimation and Costing",
	"Highway and Traffic Engineering",
	"Design of Steel Structures",
	"Structural Analytics-II",
	"Water Resource Engineering",
	"Effective Technical Communication-II",
	"Environmental Engineering",
	"Computational Analysis",
	"Railway and Airport Engineering",
	"Foundation Engineering",
	"Construction Planning and Management",
	"Chemical Engineering",
	//mech E-3
	"Design of Machine Members",
	"Dynamics of Machinery",
	"Applied Thermodynamics",
	"Non Traditional Manufacturing Process",
	"Mechanics of Composite Materials",
	"Managerial Economics and Financial Analysis",
	"Environmental Science",
	"Production Planning and Control",
	"Theory of Elasticity",
	"Design of Transmission Elements",
	"Heat Transfer"
	//ece E-3
	"Digital Signal Processing",
	"Computer Architecture",
	"Analog and Digital Communications",
	"Numerical Methods",
	"Digital System Design",
	"Micro-Controllers and Interfacing",
];