let suggestions=[
	
	"Artificial Intelligence",
	"Computer Networks",
	"Information Security",
	"Data Analytics",
	"Data Base Management System",
	"Estimation and Costing",
	"Compiler Design",
	"Soft Skills",
	"Signals And Systems",
	"Object Oriented Programming Using Java",
	"Formal Language & Automata Theory",
	"Operating Systems",
	"Principles of Marketing",
	"Personality Developement",
	"Graph Theory & Combinatorics",
	"Data Mining",
	"Soil Mechanics",
	"Highway and Traffic Engineering",
	"Design of Steel Structures",
	"Structural Analytics-II",
	"Water Resource Engineering",
	"Effective Technical Communication-II",
	"Environmental Engineering",
	"Computational Analysis",
	"Railway and Airport Engineering",
	"Foundation Engineering",
	"Construction Planning and Management",
	"Chemical Engineering",
];